#!/bin/bash
#
# Help
showhelp () {
cat <<eof

  This script is used to calculate when it's "5pm".
  It calculates the time that the user can leave after working the defined workinghours.
  This is done by using the time that the user first logged in.
Options:
    --more | -m      : Show some more output.
    --quiet | -q     : Don't show any output, for running on startup
    --workhours | -w : Set the workhours, defaults to '08:30'
    --debug | -d     : Enable debug mode, aka echo some params
    --start | -s     : Don't use last to get the login time but the current time
    --version | -v   : Get the version
    --snappy | -sn   : Get a snappy comment back
    --traffic        : Show the current traffic situation

  Configuration based on a daily fasion can be done in the /home/$whoami/.5pm/config file.
  Here one can add days where there are specific options. This is done in the following format:
    Wed=--workhours='07:50' -m
  This line sets the script to use 07:50 as workhours on Wednesday and also print more output that day.
  The matching is done based on 'date +%a'.

eof
  exit
}

# Methods
debug () {
  if $debug
  then
    echo "Debug: $@"
  fi
}

error () {
  echo "Error: $@"
  exit 1
}

# Params
params () {
  # Optional params
  if [ -z $debug ]; then debug=false ; fi
  if [ -z $workhours ]; then debug 'workhours not given'; workhours='08:30'; fi
  if [ -z $quiet ]; then quiet=false; fi
  if [ -z $more ]; then more=false; fi
  if [ -z $starts ]; then starts=false; fi
  if [ -z $version ]; then version=false; fi
  if [ -z $snappy ]; then snappy=false; fi
  if [ -z $traffic ]; then traffic=false; fi
  if [ -z $routes ]; then routes=''; fi
  # Needed for script
  installdir=$( dirname "${BASH_SOURCE[0]}" )
  trafficcliscript='/home/bjanssens/Inuits/Scripts/Trafficcli/get_traffic_cli'
  # Params needed for config
  username=$( whoami )
  # Directories and files
  currentdir="/home/${username}/.5pm"
  configfile="${currentdir}/config"
  # Check if users .5pm directory exists
  if [ ! -d $currentdir ]; then
    debug Creating "$currentdir" directory
    mkdir $currentdir
  fi
  # Tempfile
  tempfile="${currentdir}/.${dateYmd}.tmp"
  # Param checking
  regexHHMM='^[0-2]{0,1}[0-9]{1}\:[0-9]{2}$'
  if [ ! -z $workhours ]; then
    if [[ ! $workhours =~ $regexHHMM ]]; then
      error Workhours did not match the expected format, please use "hh:mm"
      error Regex that is used to match agains: $regexHHMM
    fi
  fi
}

# Read the config from a config file
config () {
  if [ -f "$configfile" ]; then
    #   %a   locale's abbreviated weekday name (e.g., Sun)
    currentD=$( date +%a )
    for config in $( cat $configfile | sed 's/ /+/g' )
    do
      configwunder=$( echo $config | sed 's/+/ /g' )
      #regexConfig='^(Mon|Tue|Wed|Thu|Fri)\=((\s{0,1}(--workhours|-w)\=\"[0-2]{0,1}[0-9]{1}\:[0-9]{2}\")|\s(--routes\s*)|\s(-m)){0,5}$'
      #if [[ ! $configwunder =~ $regexConfig ]]
      #then
      #  error Configuration syntax issue on line: \` $configwunder \`
      #fi
      day=$( echo $config | cut -d '=' -f 1 )
      if [[ "${day}" == "$currentD" ]]
      then
        configOpts=$( echo $config | sed "s/$day=//g" | sed 's/+/ /g' )
        parse_options $configOpts
      fi
    done
  else
    debug No config file found, using defaults
  fi
}

# Format the Seconds to HH:MM
# Requiers one arugment: xxxxxxxS
parse_nice () {
  S=$1
  H=$(( $S / 3600 ))
  M=$( echo "( $S - $H * 3600 ) / 60" | bc )
  if (( $( echo "$H" | wc -m ) < 3 ))
  then
    H=$( echo "0${H}" )
  fi
  if (( $( echo "$M" | wc -m ) < 3 ))
  then
    M=$( echo "0${M}" )
  fi
  echo "${H}:${M}"
}

# Set times
cal_times () {
  # Time stamps
  dateYmd=$( date +%Y%m%d )
  currentH=$( date +%H )
  currentM=$( date +%M )
  workhoursH=$( echo $workhours | cut -d ':' -f1 | sed "s/'//g" )
  workhoursM=$( echo $workhours | cut -d ':' -f2 | sed "s/'//g" )
}

# Get the uptime
# Check if the machine was rebooted
get_logintime () {
  if [ -f "$tempfile" ]
  then
    logintime=$( cat $tempfile )
    debug Got uptime from tempfile
  else
    if $starts
    then
      logintime="$currentH:$currentM"
    else
      logintime=$( last | awk '{ print $7 }' | head -n 1 )
    fi
    echo "$logintime" > ${tempfile}
    debug Wrote logintime to tempfile
    # Clean up old tempfiles
    find $currentdir -name *.tmp -ctime +2 -delete
  fi
  debug logintime: $logintime
  logintimeH=$( echo $logintime | cut -d ':' -f1 )
  logintimeM=$( echo $logintime | cut -d ':' -f2 )
  logintimeS=$(( $( echo $logintimeH | sed 's/^0//g' )*60*60 + $logintimeM*60 ))
}

# Calculate the time to leave
get_leave () {
  leaveH=$( echo "$logintimeH + $workhoursH + ( $logintimeM + $workhoursM ) / 60" | bc )
  leaveM=$( echo "( $logintimeM + $workhoursM ) % 60" | bc )
  leaveS=$( echo "$leaveH * 3600 + $leaveM * 60" | bc )
  leave=$( parse_nice $leaveS )
  debug Leavingtime: $leave
}

# Calculate time remaining
get_remaining () {
  currentS=$( echo "$currentH * 3600 + $currentM * 60" | bc )
  remainingS=$( echo "$leaveS - $currentS" | bc )
  remaining=$( parse_nice $remainingS)
  debug Remaining: $remaining
}

# Calculate the time worked
get_worked () {
  workedS=$(( $currentS - $logintimeS ))
  workedhours=$( parse_nice $workedS )
  debug Worked: $workedhours
}

# Get version by getting the amount of git commits
get_version () {
  cd $installdir
  version=$( git log | grep commit | wc -l )
  echo "Version: 1.0.$version"
  cd - 2>&- 1>&-
  exit
}

# Print the output
nice_print () {
  echo "It's 5pm at $leave"
  echo "Time remaining is $remaining"
  if $more
  then
    echo "First logged in at $logintime"
    echo "Workhours set to $workhours"
    echo "Hours worked are $workedhours"
  fi
  if $snappy
  then
    snappy $leaveS
  fi
  if $traffic
  then
    get_traffictime
  fi
}

# Make some snappy remark based upon $remaining
snappy () {
  # 8 hours remaining
  if (( $remainingS > 25200 ))
  then
    echo "You just started!"
  # 7 hours remaining
  elif (( $remainingS <= 25200 )) && (( $remainingS > 21600 ))
  then
    echo "Seriously, you just started!"
  # 6 hours remaining
  elif (( $remainingS <= 21600 )) && (( $remainingS > 18000 ))
  then
    echo "Already tired?"
  # 5 hours remaining
  elif (( $remainingS <= 18000 )) && (( $remainingS > 14400 ))
  then
    echo "Trolrolrolrolr..."
  # 4 hours remaining
  elif (( $remainingS <= 14400 )) && (( $remainingS > 10800 ))
  then
    echo "Luckily your job isn't very mentally challanging."
  # 3 hours remaining
  elif (( $remainingS <= 10800 )) && (( $remainingS > 7200 ))
  then
    echo "Don't you need to be working?"
  # 2 hours remaining
  elif (( $remainingS <= 7200 )) && (( $remainingS > 3600 ))
  then
    echo "Keep working, working, working..."
  # 1 hour remaining
  elif (( $remainingS <= 3600 )) && (( $remainingS > 1200 ))
  then
    echo "Hang in there, you can leave in about 1 hour."
  # 20 min remaining
  elif (( $remainingS <= 1200 )) && (( $remainingS > 600 ))
  then
    echo "You might want to check the traffic report..."
  elif (( $remainingS <= 600 )) && (( $remainingS > 300 ))
  then
    echo "No one would notice if you left now."
  elif (( $remainingS <= 300 )) && (( $remainingS > 0 ))
  then
    echo "You still working?"
  elif (( $remainingS < 0 ))
  then
    echo "Do you need to compensate for something?"
  fi
}

get_traffictime () {
  if [ ! -f $trafficcliscript ]
  then
    error get_traffic_cli script not found
    exit 1
  else
    $trafficcliscript -r "$routes"
  fi
}

parse_options () {
  while test -n "$1"
  do
    case "$1" in
      --help|-h)
        showhelp
        ;;
      --start|-s)
        starts=true
        shift
        ;;
      --debug|-d)
        debug=true
        shift
        ;;
      --more|-m)
        more=true
        shift
        ;;
      --quiet|-q)
        quiet=true
        shift
        ;;
      --workhours|-w)
        shift
        workhours=$1
        shift
        ;;
      --route|-r)
        shift
        routes="$routes $1"
        shift
        ;;
      --snappy|-sn)
        snappy=true
        shift
        ;;
      --version|-v)
        version=true
        shift
        ;;
      --traffic)
        traffic=true
        shift
        ;;
      *)
        showhelp
        ;;
    esac
  done
}

params
config
parse_options $@

cal_times
if $version; then
  get_version
fi
get_logintime
get_leave
get_remaining
get_worked
if ! $quiet; then
  nice_print
fi
